# Generated by Django 5.0.7 on 2024-07-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('draft', 'Draft'), ('current', 'Current'), ('past', 'Past')], default='new', max_length=10),
        ),
    ]
